# .sops.yaml
creation_rules:
  - path_regex: \.sops\.yaml$        # niet zelf encrypten!
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
  - path_regex: .*\.enc\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
