apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system     # of jouw eigen bronnaam (van bootstrap)
