apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-storage
  interval: 1m
  path: ./infra/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system     # zelfde bron als hierboven
