apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/storage-minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  # Als je CSI-driver elders deployt, kun je dependencies instellen:
  # dependsOn:
  #   - name: csi-driver
