---
apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-ingress-nginx
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:ybPFvPJ70EpgjXWa9edY2b+LxjkviJUkq039M1vVD1DS0LEyyOHdy12O5uJWdTE3JaPK1eoH8QjL/1Ve/O4JEstQxiH5XFXmnrl3p4XXGKNmIUbOi2zQ4wWk3e7NJGRW6gXvh35s66aP1JUUyaNMwLigf/B7cwCUOW9uQ73ot94U4H6PI4d1uSg4A5al+C+Dshn7ugfCrDz2lQX2D08FWgpkKqq12/VDs8M1/eVh7ED7Uf2fwfpQ5h9in1Se/D0Q0OqfoPgumEytnWVkpJA5ZXL8UJSycZYs16pTSpUvaNrmaz+0W3rpnXLkZ5yRSbETlVsAXep6JmGhCjTw0SVihPagw9ycAh/Z3PLHXnI43epqifChCPQLVO/YMF85adTZhs39PbzHzrRoh1f1TlAC7dJlkl/AOUWYUOwsmqcYO43RsMEJRlDtqRWW2audlXriQJ5g1L509pqrc9gwWdeCOT2xxm9/wFwhOXi1c7CJ3VUYXeGm6iSCG9ofize6NAraJ0BoO6uWc4f95FXJGRgBZ0Iyx8ktCi9sG1/uZ6sa22/lHFU=,iv:RmVTrHG7klT0Ihuew47y6s2DSsLk8jUQ4asVmMXqGzU=,tag:Fu+vQCZ21G568JZtC9qvzw==,type:str]
  identity.pub: ENC[AES256_GCM,data:QqiFwc3EgNo/WEUA0UcavQNxbfXMLMbu+Etljj1YtlReyhwouJvDQ85ODJ68tbwwFQvhW+HpjZw/rs9LEn9iLPURaooFuHOpScCU36Ua4IHw,iv:uNMT2OL0kJeFpuMSUyxH5Z0MUXlJSVWTLrEdSU6MHko=,tag:nX9u6uQecAy0wgg/YFz6gA==,type:str]
  known_hosts: ENC[AES256_GCM,data:2qKIFBi0bO007GxZJAcDEByOpl35ZD8TGN6V9+Fxlbt5Mb+08AcqQ3PupHxZvTwr8Kv4/moIMyDyXms0uRZmPijT1UNMuqtmGWSyxiirn+HHqlLqSd0iENQcOoOFK/mKXpiW+Lhmhrqy5LtCF4KzC6qylrlibBveNaKlXNdtpDopmS2hzoXomI/bSr6ZHoKfm5s1GXZYh8rK4+Y4xTjV7f0tLLLQNzP5Pu/0,iv:lUlrn0wqcNp6CC7QQ3ZNC3+NGM82NnchLptnzTJVW+E=,tag:UiYmRv+iWgdWD7YHdrfhgw==,type:str]
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucnowWS8xVzZZK3hxN1E4
        M3lnQTREdldhRzUrV05sWkI1bHZGUWE0U1h3Cjl6NFJCMXIvczVabEhVYkRZVFlv
        RHVWMUQwQXBJdXFpKzlNdUZNUE5yaTgKLS0tIDlHVE0xVXJIblJBcG1TRmg0NmYz
        M3BMaTI3eUc5OUdqOHpodk9uL1BvNEUKfOUwQ2235lqVRBSqVkY7q2ub9GXRjznu
        rzwE9g1DEW/Y8oK8ZnUna1ZBh3CislKcF5skJrW5sXJi+bF5dpG9Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-11T11:00:21Z"
  mac: ENC[AES256_GCM,data:R/sROBt4f7eKj5c9DOUH19tQkP3w0EMSJCaATD3QbaUMQSRypdNOdKKzBgHnsN09tY/ZagoZJWJPR9nHbkcKQFoa6/KB//oQAfWuqA24WMSykQKsh3YnWbCmo8QnCPqPngDQEXaHhVZ8aEEgmfC+l2DUr4Ra0bhydS0sFlA/XEU=,iv:fxnpJkkQcxpFmzK4fptzUG/C31Nuq67C8tHAsnnJnqo=,tag:WTNBGtDiEPQ0B9ZipuY5cw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ssh://github.com/enschede/transip-nginx.git
  secretRef:
    name: github-deploy-ingress-nginx

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  # Checkt git repo van ingress-nginx iedere 5 minuten als deployment goed is verlopen
  interval: 5m
  # Git check wanneer een deployment niet goed is verlopen
  retryInterval: 30s
  # Folder in de git repo waar kustomization gevonden kan worden
  path: ./deployment
  # Zorgt er voor dat oude bestanden zijn verwijderd in de git repo ook live worden verwijderd
  prune: true
  sourceRef:
    kind: GitRepository
    name: ingress-nginx
    namespace: flux-system
  # Geeft pas ready:true wanneer alle checks prositief zijn verlopen. Belangrijk voor een dependson.
  wait: true
  # Activeer sops provider
  decryption:
    provider: sops
    secretRef:
      name: sops-age
