apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: secret-agent
  namespace: flux-system
spec:
  interval: 1h
  url: oci://us-docker.pkg.dev/forgeops-public/charts/secret-agent
  ref:
    tag: v1.2.11