---
apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-cdc-client-2
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:RN66G3UYTp0bHEgwyKHFfpomfg5GSXTNbCc/Sf74e0dShCqUgusVB6qxLWtzwQkZ+wul8sUicqV543F2+PxXD3n5VoX1IiiW7to7QgWnS+aMIAKthWbs4jFe5RZs1Q9L0bHBcoF2O7X/kLEo/hTqxMOuOLKsqMiF50nCfDWTIFsdJYEdhk6ZbsRjwwvpgjLbxZ0EFEbuqk+vL9z3bJI5xZIiF5l2VoI4ZFlc0mC0mbV3iU0Yi3eTWTit6/XTNj2qldwczVLojMssLWXiA+ROBblsekf6E89tHU86J59niBfeWeS6+eeG4aNfpaFfTskbkkEUwTwTKmeBPs6f7tXZQ89I5UDKmGcTC5icloSn0yyjfyr/DnVAItoZVp7hWWrD0BZuXiC2C7Ydq8Hz7o/+QbMZQl63eTYRYhz7akPFJumSGUAYNv16UXSftmv7Qp4X+02JbpH4ooHGvT1TYwXk9IlRsua55ykKywn+/pBeX55pvTJqfwzy8xNzz4Mmmg6NiPUdyCZAmmdFAQrBKK0ES6RjWnp10uxJN10uv8z2lpkoaVM=,iv:E5fmhjrWaH/YaU3wKKg7ovzejRdelARF0DezLRLu+Qo=,tag:uz3W3uuIgovTyjiVflkHMA==,type:str]
  identity.pub: ENC[AES256_GCM,data:BtGteRMplzcExzRowmQMhKxtgG7Gr+lhsI9jFzkJOtUh0TjWTEf+lj/Hvi7Vgb9uuMs7i0IzTdqDV/QzplKYt7ElsBZwVi/gf6MsU7eQzrgA,iv:iWBL4AtLjnJ/0XNE/fRflpW16G3B78woFdibWRUv8qY=,tag:1Obk1n5sSgiQzYfYesUuQw==,type:str]
  known_hosts: ENC[AES256_GCM,data:ThzGiyCvJ7s/T2uI0Kgs8+Muhh2GN6NU1udSxttV7QfWlm+nElt3coUchMYNdLWsdb69L1e2xT/0mo/yu2AxV94msrPa/X6gEvNK5YGWbe7yQk1fsrcKXONUWqk9KpvD4m/aK188vnrdQpNbFtYuFi/L2nvwYCtQVKa/6te1jIKYCVZLCTGOC7y+EcrbFVKdInnDHoUO7Y57SuWYLlJZy368DIqpcjMzCa2H,iv:UpBG/7jBoii4uzosuQY7atEeVBTBBkl7LnoNclXmwKA=,tag:w+OfA1Odm8/mabS5uhs4BQ==,type:str]
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a3dyTGtyZWZoM2xvUW1B
        R0tDU21QTkNJaFoyNjNNYkNsc2NxMi80UEZrCmJHd1BjeGpSdGpMTDh3V0NibWZK
        MWJ4TzNEOWZsNnpMSzQwYUVtdEdSVUkKLS0tIDZCWWxkMWdvcHRqVlMrRGVxYjlC
        K1FJWlk3NzRieHZnN2lQOStNaGpKTmMK0rcHizgDaDXc93Ltwa3DIXBu6OtI4OvI
        DVhFiYVtBT4toq7oXseob7M7g96kKV8oGqi+FcZKqNCUY8X6QAePTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T13:43:06Z"
  mac: ENC[AES256_GCM,data:EoZYBQyO4yQjYT1KxAbt4+HFQyWmjwVSJL2BrBaiv8+bge3LpaBSXGkiT4HOe0bX8a+cxHjD7KW24UqR0XjWxyeDDpld86ND0lrmNNO6ofiPIlV7kKyCS6sFe7aoDIBjdqiWwaZTppOH42w5yVSKFeTPc++XYtv1Rop0+jeewkQ=,iv:xPvNPnozeH2DvmTAXL7Ual2IGsHEQ7UXm5TvxFTeXgk=,tag:PrFB8jt5dDJRER5UYLKA2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0


---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cdc-idm-client-2
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://github.com/enschede/cdc-idm2.git
  secretRef:
    name: github-deploy-cdc-client-2

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cdc-idm-client-2
  namespace: flux-system
spec:
  interval: 1m
  path: ./src/main/deployment/overlay/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: cdc-idm-client-2
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx

