---
apiVersion: v1
data:
  identity: ENC[AES256_GCM,data:rBU8euvssrDUiRlKzcxTdqaOLvU+rEFKhS1kJfjI9VOVefFaWcxqI+XeXWY0TwZdhQEZO7GSdVQ++fMcc6qclL99Y+qNc3JiP8z4TAE+1BwN/DqOYqtl6f3YKI0lv/eAQgx2Z1rA7eVkBPnEhhDrx5SJncPcSOQCRgYtNMD5Z27sNL/q7vhLp1iF3kmAp5JWjZUt+KlNZW+lPl7Zu+HvQy4Y7mr9A/XOXIUkyUh6hEoZzCY2Sd2kPZ1gRxPeK5TA67RpEDdM+aTIu7NTDAQqvFGpltpEtOgThL02vi49o3h2u+8brSq6Ym1gQIsYI8kPLgKOeRAQ8o02wclAnyNRWxlsa3bl8pNPws5fSgebdzMugkdND+E96M+PKwy5SDH61u3MYKDmsZRsZkVJ6Gy8WU1Vzu3X1rT2daYIewdfWGgQIotHq3HAetV9/YwtzI/PS9rlbvgdRP6XbY/K+REeINlzpLNojkfMMbbJ5JhJsUC8BlO11b3mtJJbzm6KLsAZL+NSFuph/ClwuKp2R6RXH+idF9ScuhqaU9cL+hHB2/JzDzFYXsXDpNGUr7uedusxTfaEbmpu2ERyWWX33MGs1eydh805PFi3335wYghXdtPhAqQKRGQtQIhshdrEAwHcvQMuPb8MR0sFciDwwhMuFBKBD5TK2xgHqukIizx7lO1RSqzOKuuSXmj81TJQgNAeF+hJlIFxd4OV4IAwSHCOvj++rJcVlJxH49Xrr96m5P9/L+RTuRpaPLmJf1p5rJz+,iv:aY7EWOp5oTGxePbt715HccqR5M9rf1O+bhfBiTeNHCE=,tag:73a7XbP18g5oJJ8V+ZxzaQ==,type:str]
  identity.pub: ENC[AES256_GCM,data:h/dY9itPklG0x6p5/djzNs3j8FGVdJ+Eo04xaFyM4danac2PRf8eXXAyUCuCYO6k687HYKKlbYqWBEzQFwufszIO0NI/LDkO3o8FbMvdTW9mu0yzRtD/ERf00ZldWcMYKIGRnxdakBRQq4SU/cdLIw2XDvd/xg0Y8fldC1ereoI7hiQ0EhXOFkUant9Y7XbNR25/V65A8zE=,iv:w/vAru3pemHz0XJEZ+/ZaQoU4RS2sJq6Y19m7Y4kBIY=,tag:dC/kvcTtXTnPxR0XmgIQNA==,type:str]
  known_hosts: ENC[AES256_GCM,data:8ROTuYpOP+f5djc2NdIOZG2tBMkQcym9DQrs8trDZHfuftAdjq4KU0RjhTfGkp4+7JWq3/97PhXen7J18eyTcIVXUUa5VwzqqFr9Ll6Z88R7tSxFUSk3LAgOKbg3OHn8tTW1m1DEttTNaHeiGBjrsjv/Kx5HgBRdDddfyHfjr6tRnUsErCe2yMVtIRlRzey62Wpt9S7bsedbQH8h15Hi56I6XimfNfsBci0yCnzB8+O3hqi4U8A85/wNPfQwVZLI+S6Xsa4K+0CSdwmUaaLAgI5rrxy+FHWA21C2ps+h3OiiBkVn6fjDJdap+MZWesxoXazKZWg2cWpdHj5pbAEaLkfjIjEypXl03sGCWuW42mE24ewULvbiOLMWnIr52LDnyFDFiJEdxinKgY3HuDw2vVPs2wJC609VttI3Z273LAq4iix2hsChkm8lj38dFMrolzpSZdRk8NJCwUOHh6aPltllnaBsNiCFivx//fl2lTDh6cLWsr5YnuuzYdI8ZIzMijXQNrHZvFSDISQCw/BoTT3vMSxo67ZMrT6g0d2MHwpSefzPaMBVxIMw7Gzyntzl0ebzWDMdqNrUmXNmMRKZ+Bc1qZuMhOE677LR3oTusjf/PT1UuRv8lT5Cx5ZeQ4Z0RkAxLrZUQgALil4+zZ3DLNWyoVNdqaGOU3ccV6Wa8J/dG9TgJqTb5any2ElWnsXQyIuPfjoc2wlgCYqvf+qc4VnFh+NfzL0i2UWGMMBzqXOwW6+y2BuCHTfqvnJxEp4ys/Twibkhi9yngjhDoUkGrPa1ljFM8BGzjWlo5eRDGsiJJsXBYX11B7e4ZXlIIdkmq5QVPguBNgemG8u/l12TIZb77Itpg5NCk/OyZVfWYsT/ekvguP4OvMwq3Q8CFc0in8XVwnJHAwU+xEnSxyooEu4bGAJXKLuzrA68DKpalPAXsLwap+NogDzHYeWdBZwcZ18xqcL7weVwc3ohTxxqkMZlkS/taSXPfEYE084uJn8QnOiIOFqnbHiEMy/Eou9Wf35Oya4G3PNPlMMPoY7l0bLNpP10EQzgOQPYTgIx2S3hrntoqpcsiqmmL9MTxCGbHMXhHJhfGkhonQLh5Wvlr7W/zSegl0jZHqQSzcbfBCYNbqVnx1PaTpV9jCQhvo3tzAlkv0VTxHYbcI+GHet03bEnVhxaUbKEyhzfmcr4OSZ7wFXAu5IEs4XwYqJLC0oCocttJcNxn59UISQUXbVmx9rc4gHQOZj1YnaTBmlsaDNiRYveX08uSu9j8msBF00bnPvH6y5tIt70Sn3EonYdtXxaO9nnoz7lcucIkgxnqJxYV7tat0z4tJ3HOwbkhwxz6Uf9CNjIylxoisEGCY0jpQuj4LXGx8Vmk6upMCJjGGuo+ikD0kvjYn54uRdfRBA70APJS9EJ3pNdAXK8cF7Q1h+Z41j8xC1/OH/xpKfVmZ//sZZxIG24YIMfiZv+ksnFgMpIfTXiyHAz6eCa77IsciIZU5QS7LkNPRG1ju5QE2onpdF5cFTLz/yKEbeHhqDQZGwuUoW6XJpMmron1Qz8HCAamaPnijVLV9P573GGBqwQjMs2NlpQyX4UcpAP7Cwp7vC/c0nxqnUZjSAFhw35H7PFbYeHu5HOCIOwFFQ7IneyTb1cWSt+u7+FJMZaMpZbTv/FGnwa+egNej9dvCvY7WlGXzQKOgOSohngmUo6+6DeY/U3lnNnpwezkLY+nTKRc8Mqw+mh7lyRJyTXgs8fiTPSqSIGsnZW,iv:VVCVrNHT4SpNYDwe2ZgluKm6QLFF5yNT6HDoQgamZQc=,tag:SGXxFbzwudMFFJoFS/MU0Q==,type:str]
kind: Secret
metadata:
  name: client-app-deploy-key
  namespace: flux-system
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMHl0NGtZYXljRGE0czdW
        SWlPL2VTejd6UEEraXhDeEZ2ZTB6NTFkYjNzCjZ4Z0VzeS9mc1pQMElLdW9BUUln
        VWE0MnhMbjhCazJDRkFNNER0NnZrdzAKLS0tIGIvTnRGRTdKU1BsSTh3WWw0YnJI
        c0xqNWZBYzY5QkZyT1h1Z2g1a2JVOE0KVG3fUobbqLy/LYE62T0Qm1cksf7/JTIB
        SMVqWH1J+VfQW0rwmkzB8OhGzTzuMtg7zcEWkiROyE8eggtOUZoYDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T19:17:43Z"
  mac: ENC[AES256_GCM,data:xnaBZKdpvKjQMpN0gXbaH/hVBNe8HjsCYBigw51NIe1FPk/puiKKXhgVSnh1/o8kbGKKSmxuA6318Y3TXWBpzjyef6g1zvzaSJ8sboXbHs7gnDTC7XPkgdWECt3B4poHgVhGdV1qIJFo2F/dETpNsPkMTl1Jjazex5WRr8J0Dxo=,iv:zQJXc0MZLPUIWTQG/crOa9J6Qy45TjZ33BVb9sCy1E0=,tag://cCiAlXVbfbQtUS9pmrPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: client-app-git-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://github.com/enschede/OAuth2ClientAppDemo.git
  secretRef:
    name: client-app-deploy-key

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-client-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./src/main/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: client-app-git-repo
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx
    - name: forgerock
    - name: oauth2-resource-app
