---
apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-ping-infra
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:HOYC/C6ukpl4bcmiRtAiOR1jlNPfsoMNO81hbJIGixdIE13qq6agJ2hXHiwvke0nJRZxETv2Y1CrIGMwHdsjJNIzRsZ53hCs/KQy6aBuuYHrhYYz9rcBzQUgCTLnrD9H8o8j3zhySzNKQ20gdMgeRCEkByRdy1x4ooZTzt3Tua2gk1hQ/oWCWVFvw+EO6q1zxEAf3M7pfJewJg3CU3Ro+4Txx9IKkIFWLC6GFLLKEEYaTj7AzBRUAQ9DuyfPEQ1EhO67p7OKYKxpvb5JXkbIu7wgYoy8h8cITjoQX0eU6R3jQxo5c8xmWvVmH+pRiMqs1Sg60I6kwuDhoisnFzNOT4oGKxVjcBPy6c1mKMkFKU0tgoXbbEf05g5D6snHq2MG4VMRQusDxtkqdm7ZZSNd2wrC1Wm9sDNrkNnI54gyYtpFOAbd9JUHF1cJXmoajJC5pbrXj9al9NjZto+EXERcJ52YBSTzSLq52WzQZayRKo/K6OpApnGyNa2F4c2VdIR06s/NzhvFdNt4+Blt6DKHNfYM8k+f2lTjCUYyVAUQ7ddSEss=,iv:Zp5+n/eSyodVLZ5Gr7IWpY0PjXr8TLZ3TLJijvAjmfo=,tag:2E8YIDvFFFBfipHlfewy2w==,type:str]
  identity.pub: ENC[AES256_GCM,data:dQPEjRWd4TpHQh2iQi0XorxOv307TGkCphDQ7zGpwIL9nLZP2qAQHiVBYTjNpbTeW+3u1wjFbyqYOB/gl6gAFoDpk+1GqeEhjsWcZ4UZ2l4z,iv:8+7FT/55WT4NPYtWcbXhky/iwOoGIj7eMNDEH3ZMlWQ=,tag:ue9eI4VvGj0yHB0xc7BZlQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:HfpyuMKZm13Lsm50vrXYj9K3xrDxmETRb0XJ6NH0E4Mr5W088vglUyuhvEqZpu/w3Ue5kQNBOpGgqNpFfDbNbh4tF03oezJDpzV1oNrhb6kYPVDIO2JuezskfXw/fouGEnWuUQ+kkt9FJomA6OboDqONZAZKE3caU41HLCCYcuGRpb+hnUrBPQag50Ul2ZvkSZKdrpWcQKc0qIPKhTZy60D8TpTl+M48AJnz,iv:otzRD9u/MpK1EJu28ovuQ983TDqA5IoqNhHWjh94QJc=,tag:rwg3m3loagLrhn+xj7jCWA==,type:str]
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ2ZpWXRsVGRjN0t4VmJ3
        OUdiK0hhaDhkT2dmdFVrWjQxcjFxclJpK3drCnpXb3ZVVDBTTDIrcUpqNE8vUXRV
        N29JWUx4ZDZRV2hJTzE4OG9zUm9SYXcKLS0tIEVuTndMQ205b1hKSTVSMnJVSi9T
        QVY2S01Tb3BobUxzeS83alVpNk5yTG8KVOn22u/3U1+GdOd8sfV14ICuG7PGPwEo
        OWoG9peDBj3fTZB02OPqUpsTGx5qlshkcMoax05Hi5SYoifTQAMGMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-25T19:27:29Z"
  mac: ENC[AES256_GCM,data:IvM6yQKmH9e1FJNp1zWNuWq7xqUtaRhPDo6w9cCgEreBo03kvYYvjiCc3WpKuLK4ni1DXgSQ42jOmyt/5HtbO3TDCiZpiSsgEO81loz6YhYFp5aG56UxYFyHlA2ftoVIB+xqbk54gLZUH3k2Cj7+w7QZkXPO4IhdM7RrT3gXSPU=,iv:5s0NJ5/mhC5Pe+UzaoZ2Wf8tJIC2Fkraa+R+fQaZ0x0=,tag:BTlvHJ2hD7MBSpTK0Oz3sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ping-infra
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  url: ssh://github.com/enschede/transip-ping-infra.git
  secretRef:
    name: github-deploy-ping-infra

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  path: ./cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: ping-infra
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-agent
  namespace: flux-system
spec:
  interval: 1m
  path: ./secret-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: ping-infra
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx

