---
apiVersion: v1
kind: Namespace
metadata:
  name: forgerock

---
apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-ping-infra
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:HOYC/C6ukpl4bcmiRtAiOR1jlNPfsoMNO81hbJIGixdIE13qq6agJ2hXHiwvke0nJRZxETv2Y1CrIGMwHdsjJNIzRsZ53hCs/KQy6aBuuYHrhYYz9rcBzQUgCTLnrD9H8o8j3zhySzNKQ20gdMgeRCEkByRdy1x4ooZTzt3Tua2gk1hQ/oWCWVFvw+EO6q1zxEAf3M7pfJewJg3CU3Ro+4Txx9IKkIFWLC6GFLLKEEYaTj7AzBRUAQ9DuyfPEQ1EhO67p7OKYKxpvb5JXkbIu7wgYoy8h8cITjoQX0eU6R3jQxo5c8xmWvVmH+pRiMqs1Sg60I6kwuDhoisnFzNOT4oGKxVjcBPy6c1mKMkFKU0tgoXbbEf05g5D6snHq2MG4VMRQusDxtkqdm7ZZSNd2wrC1Wm9sDNrkNnI54gyYtpFOAbd9JUHF1cJXmoajJC5pbrXj9al9NjZto+EXERcJ52YBSTzSLq52WzQZayRKo/K6OpApnGyNa2F4c2VdIR06s/NzhvFdNt4+Blt6DKHNfYM8k+f2lTjCUYyVAUQ7ddSEss=,iv:Zp5+n/eSyodVLZ5Gr7IWpY0PjXr8TLZ3TLJijvAjmfo=,tag:2E8YIDvFFFBfipHlfewy2w==,type:str]
  identity.pub: ENC[AES256_GCM,data:dQPEjRWd4TpHQh2iQi0XorxOv307TGkCphDQ7zGpwIL9nLZP2qAQHiVBYTjNpbTeW+3u1wjFbyqYOB/gl6gAFoDpk+1GqeEhjsWcZ4UZ2l4z,iv:8+7FT/55WT4NPYtWcbXhky/iwOoGIj7eMNDEH3ZMlWQ=,tag:ue9eI4VvGj0yHB0xc7BZlQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:HfpyuMKZm13Lsm50vrXYj9K3xrDxmETRb0XJ6NH0E4Mr5W088vglUyuhvEqZpu/w3Ue5kQNBOpGgqNpFfDbNbh4tF03oezJDpzV1oNrhb6kYPVDIO2JuezskfXw/fouGEnWuUQ+kkt9FJomA6OboDqONZAZKE3caU41HLCCYcuGRpb+hnUrBPQag50Ul2ZvkSZKdrpWcQKc0qIPKhTZy60D8TpTl+M48AJnz,iv:otzRD9u/MpK1EJu28ovuQ983TDqA5IoqNhHWjh94QJc=,tag:rwg3m3loagLrhn+xj7jCWA==,type:str]
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ2ZpWXRsVGRjN0t4VmJ3
        OUdiK0hhaDhkT2dmdFVrWjQxcjFxclJpK3drCnpXb3ZVVDBTTDIrcUpqNE8vUXRV
        N29JWUx4ZDZRV2hJTzE4OG9zUm9SYXcKLS0tIEVuTndMQ205b1hKSTVSMnJVSi9T
        QVY2S01Tb3BobUxzeS83alVpNk5yTG8KVOn22u/3U1+GdOd8sfV14ICuG7PGPwEo
        OWoG9peDBj3fTZB02OPqUpsTGx5qlshkcMoax05Hi5SYoifTQAMGMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-25T19:27:29Z"
  mac: ENC[AES256_GCM,data:IvM6yQKmH9e1FJNp1zWNuWq7xqUtaRhPDo6w9cCgEreBo03kvYYvjiCc3WpKuLK4ni1DXgSQ42jOmyt/5HtbO3TDCiZpiSsgEO81loz6YhYFp5aG56UxYFyHlA2ftoVIB+xqbk54gLZUH3k2Cj7+w7QZkXPO4IhdM7RrT3gXSPU=,iv:5s0NJ5/mhC5Pe+UzaoZ2Wf8tJIC2Fkraa+R+fQaZ0x0=,tag:BTlvHJ2hD7MBSpTK0Oz3sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2

---
apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-forgerock
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:KMD48LQtXMPQHgdJ/A8b1qbcbIY5hV3csP3FJm1I5em2XFP7/dabuxwEZ4RNb967qK9ZVDrilycXqXFAg99EC/h7Fu+EjfW9/PbxKZn+BYJwPTeYSpJaH3R7PzW8bOT9LsZey79eBAExtHuig8BwtFq1VJcUtOeUOwjgSM97smqU/cCvs+dwrf3jLwtRYzfXHDbsoXU69JgVvMgKsCbwX0neRqAvJr4h+1OzOGV2Fq4xH3c5U3B+2hkbfHQqBMAYzQ9ddRzEpXzHA/iiL93JpPMPOPhq3gXmjT2PyU/WUByVdikzId4AEfoar0QtF1iiCSxu2VyRMqrGDRBZX+LRjsu7QDjPatl8rZ+YZnXBtRVDQF4CYhDF4rsIhdtJiLDVG5Cvu6NH8Ju6sxofyy7gQ523S8MR3n7ZQDZqmRoNjPyXyYcZ7zj85TlRKGDgwwnrfwUq80q+/zG0n0IH/Q/OHv3lJby5crp6HQk5EAxx7Hppws8SKSF0oy6ltTGUvvWGqlLGecy5lrbhB5ct0an9hiIT/uGKMz1fAOxkJ8c3koZ63Zw=,iv:VMFKl1uEn1/b/CbEpFrM5z2GX9BnuAZGcmlj/l08V94=,tag:NzyhqbOlw6W5WUegyHjjKA==,type:str]
  identity.pub: ENC[AES256_GCM,data:ddcNpZQfl46fEFRG7/aBNk0zK9+QHihCSheLRQzyxVf/KmeYDEuVgv3EN9iuJwkGHkVm4tB79s9YzNizmgNLgslNQ5I9jlUgxkO2+mUVR4MJ,iv:6HTjuWVY+BbiLPFETqKMzYvkwBbVb1BeOgbYa7+jbl0=,tag:Rej0lII6qS0ksJDklg4c2Q==,type:str]
  known_hosts: ENC[AES256_GCM,data:/wxwSjpDG2jati9P9NOI3Ac511fDkncTcBTxSGvaXSbyFOQ1/XAUQ0L7vWTU97zl7x/Q/3G8GsTjZVIVSJrr9rxbyasgUcL21FYqB2uwm7bR6nMgbK5WFG/Qqg9+6yHO8LVbraCgz/UzU6JY7YjNhFsFAEUOyKp8hNANE0nzXdL0wAmcPatE47gVPn3W6ATIabs6+umSja/4GgCulzp9VhkYnaHUcOOrYeSr,iv:ItirDurdHtTZYcl1klSVbD6S8TDS/D/YadB3pr7Wllk=,tag:kTyaPwfo3jmr4VQeNXNQ5Q==,type:str]
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSEpsdEtJQVlncnhySUZm
        SG01TTdvUzZEMXlrUjlNa2pnbUt4S2tIK2pVCkhZSU50dnpNeXQvb3pMaTR4M3o3
        RzIyKzNSWWdtVGxQbDNLMXFRUWRQbVkKLS0tIFQxaERJbm5aVVN1UUFGUDN1ajk3
        T2FLbnl1bTIzVkdid2dQZEo0WVFjajgKsMZcyGc56vpvV/2iS4iS0QVERPDphd8S
        XWPuxUcvmJlHMDL8ivT6UiTfIZuvUE0iL2jzjXGPm86Lq7ed7LlTgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-12T10:38:42Z"
  mac: ENC[AES256_GCM,data:5JY+E2tQxXJjBFrihpYbnElk6Er2ETvHbcIMecY02vnajyB5UBkTqSwMuSoypjhxSG8Ir04jCbIVevozYWQbY6yuN94kO+AYrsq+/zg1xY+e7FBtfhO1okVd5DfOkAvsH6C4N2k4KtICEuzFfG3/bBcU2p8Mi+xgXmdfncAOcMQ=,iv:kPd2yWz9Oo8NA6b6lOntXvoTdf44gunXmbYB75pjAew=,tag:RilkeNUajDrIbh0COiIIvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ping-infra
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  url: ssh://github.com/enschede/transip-ping-infra.git
  secretRef:
    name: github-deploy-ping-infra

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: forgerock
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: marc
  url: ssh://github.com/enschede/forgeops.git
  secretRef:
    name: github-deploy-forgerock

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  path: ./cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: ping-infra
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-agent
  namespace: flux-system
spec:
  interval: 1m
  path: ./secret-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: ping-infra
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgerock
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomize/overlay/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: forgerock
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx
    - name: cert-manager
    - name: secret-agent

