---
apiVersion: v1
kind: Secret
metadata:
  name: loki-github-deploy
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAx1Fev2V84fNrQR4/s5rrlRUdXApKHYF23LqMBymk1HQAAAKCX1cD9l9XA
    /QAAAAtzc2gtZWQyNTUxOQAAACAx1Fev2V84fNrQR4/s5rrlRUdXApKHYF23LqMBymk1HQ
    AAAECjAOCqNDX0ml6n6D0pX1cjhNyJ2yczdoAXBtzOGilSiDHUV6/ZXzh82tBHj+zmuuVF
    R1cCkodgXbcuowHKaTUdAAAAGGRlcGxveS1rZXkgdm9vciBPUkcvUkVQTwECAwQF
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDHUV6/ZXzh82tBHj+zmuuVFR1cCkodgXbcuowHKaTUd
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ssh://github.com/enschede/loki.git
  secretRef:
    name: loki-github-deploy

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1m
  path: ./deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: loki
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
