apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-key
  namespace: flux-system
data:
  identity: ENC[AES256_GCM,data:tZUG3T42rvGOQt8ZgD315NuT4X3bEsF9eOFUSw7RMxbUterLD8fLT3cdAgxJXef2ggBBhvMKJP0VveYMb76ayUDNmSe3hXvZwQ03Xusr2/bY8MKNIeWSOZJ/l9J0oS4L3bDRq3eXNrPnZCcJFwfp25JGYpsHDyoVs3/9SUqV+KOg64oJCyQHWJ90nHJemSkj/7VFSrtY2MHUcEvtYd3VcSlQ29LnhHHx/IPorD/RqSZpzxJCZnyUewXmRB7tjZUJRm2wbxU5hOguDHt0f6Lquk4aMK07MpBm4W7RXgS6S/640aMNuuW/Xhynqgi/Opc9iB5yvHiSHHhw+h0FN3n9VsRdxSTB+bpdW4wkKkXM4KCO2LirRUvjn4lLXy+d6A/ugHpS9Q0h+PbchyGDpd0n/pYg41eoRJY8a3FURrzMKpmOgVLr7DYWT0Nf1zEU6pETlPaFQt8CICD0+JM3vb2Zkd7Oe03bGgh/yHTOGuJ8R64axiDD2SlSpIQHFNtgATr+2ZOrX+HIDNDspz2r+1WTMAj1R8SYvgJ3pnlJaL92PNKpGfL66IS9aGaCXpjGQs80Zna8HuOnflL/GG3ctCIaYzCxSZ0ndm7lX58cdXoskbAhCggxBxrKJJ0wKCV0tLuZEHdIWeeEnVzrOPwQsTrgQc3auigVhbLi3bKYC7bxXYUDy4teZXrFnmYb98Jn23gpW9qkQGz78T/rG9kqtdnz3B4ABrwjqpD4y6bIINoAnyz4Pa90ZkYLqalUWgMHahEp,iv:y6wMrbGhX7zP28Y+Dr0HXXEwOZzXfLwkhwTpLuDda28=,tag:8L6FR+4GWMI0yoIWnyVsog==,type:str]
  identity.pub: ENC[AES256_GCM,data:788DaESNahjOxZ/kzASUjKtw+J9d7a4Z/60HaBYBtcCeCWtpQT7RxNsDgk0Xj80HLu5Q4HnB+BO/TsoUeokUz6qOluONtPt8XIzxaH4Kg0w+eubn0DwJ/Qa5VEehgRGujqXqA/gTEgmoMEc2lPu41QHWuN0kSiepYPkGN/v9rVV5hB2xBsIZcGZSCm/BjPLWRcSDzOocrCQ=,iv:Vd+6sAuTJ8kNmDjZi86oRspnOv2efC/+8ZsDEQtOU7M=,tag:fUjJtmfsN6ziLJvtYLKwRg==,type:str]
  known_hosts: ENC[AES256_GCM,data:doqUL+KPcZ9wvrx4QLHU3oi1lyT+UdMlCTDmsLelAB7gOAg11EloWNhIjHxydZNF8CDq1jKeY62qswVSlKW0qwFBD32Ki2uC+jXEzSeY14iMJPd+Y73SteXJXff5v9heTf5/aonTQir+eSGLQbP19B1rimjCnIoiBkIDAlcMWdZiobuukRJ8GQhEjuaZSKTTkHNyOz4bqYnVOTaNIhveo3eo0r4zLK4wY6ijH6d4E/S8Q7dJKT6NvijGGKG8GAxx8VDDWXTjBLs9Gs6Ao+gjd2z2zdbl8/30oUZnkSn23vNYJ8BmO4lyMD/ZeI/dPyYLoqJles+erZ8EBgSBn+1o4q051KwtOzagIkLXBkD7x2dyt2smyUJ8MLx7BbgWkzOA4uQMAKkOAqbTFXSp0tvm2lHEB/c1VDcIFetY2bz/8WHKANv8VN/S0T+ZCALGhIrGPk8ACDEngdWx7hpwbyXsjK++wMEqlJu6VBNF00w2W8nD6ioo3JVipg3kuGg50tkkTcVGkDnaOApM20slfcGZU/qivd3ZKhl9dd9bwAYSUqcnme5oxTAs7w0PZroJX7rXC9NSGFK+yDCN4qD0Hdoj5dOLnXaSK5BMoIp13O4EbjeULWW6Q0SHZ8A63P8DUOvGMf8W7GG1W0MJNBD4BulC2dp0Tyz7FhJ2skNkV9yo+5Mnh6iKJ5QvlDFzENvX2em5taj8dG5W7lW13W7m6xHfCy3+BMgRZ4SOXklT+Ao1tK+XgkuXD6xj+mk2S3YFqs3tj/TvMJ7c92KclghEYjwzJ5to9+t5lvTS5fHyCfkDSNi8ryLT3VP3TUSQMNiLx2niFVssLF54ko4h91w9R7cKwzwXOxoSSxToD8Vanz7j/lKolGQPDaIrJrtBT4sLBzjhb+uAnsHNzt/Sgnp81qhkZFsEU9pA4wCaQWkhFl0eEla8jZ16busdqgnUdZ7IiVuC0aV9ucYMAz0r1lbmg7y8Jkcj3xESUio4rbOs7fA0Y1+iZsFVlirMKsZuyaT2Zma0suiRUH4e+RI2Tad+Fps+wwQNEhNto6KMdTRop/TXXLCF6LGY7lh+8TXO9c/EJkOROeK8rPbCfwOCk9VMB3fdDMZUHjoQE7rdhJO6vasBGXlWaRJCpyJw+pa/ozcZRABRcurQOgPxTrdSDkESkwwNP+tIVg/qxkpFA3NXxuS1Q2lk+Atuv4yG60NnWAy050k4LNiwC+wk9MLpc6Ik5I1xOIoVjteF1kgw2Fkt+ymz7Kjb28wtfgV9AFTdA87zaUXCo9caEgKNU99Q/hPejoNRd8MgoIYIVzAwr1pf7OrWSFba1efShzDpIIV3OmlpBHqKSY+9SN4PxVssmnBPhRmLAdJRftAZUEHxvZJTPaGNAMmvlvUtdNJ1ESyUt3xtvevTNpwBKE6pSv/LgnxrIxSBPUO9Q5/sDh0B95HmuXWXVZ6cSKiQg0auLl5ov/vmb2MMRtPFvlPPEjm8/pEWxqb3WMn6GBah1B8X1WzxB7JDcs0BVeb4QaZhyBQyLY+Ozt7Fsc3/pVliPv4E7WD+ylBMzIchUg7+vzHp7nQHG6iH979SVGcSwhS+G7AXrf8A2Yq7LplGRJNC5+lj978VIByePHL1hnvbAHF/h3zmJ/cjXLflft66QKFtUdStZ1Jf2uhKcLPXj37mg+EwHkTurwfIqSTl9v/tsAFC1I2RZTVwCBWkT+1PvIERHiI/nECvIG+b3GpzIo41IlsQH8O7uoRZ1LIqnMfn4iol,iv:ev3VKfdS2sSBZjBJWS3M5NExtFba3WwZZNvRobR6KqU=,tag:9nOu/DB5K0n4o8F8/QUerA==,type:str]
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ3R4ZDl1UStteFg0d2c5
        M1ZsZTJkZGRaR24rVEg3QUFBSUVBTkRLa3lVCm9yNktYSWtEUnpVSEhRVWgyTDc3
        bnRoWU5aeTJCNmJBNi9FL2NkV2lkcXMKLS0tIE9UUUJwTXZBRXhTa0RBRHExaWV3
        ZDVweUhoTXN5Tk5ZUkFOaHNyQ3NkdlkK7gM/+icse73xMleuQtxihnGGo9/VoC74
        XQGBcYterzP9RISIeesdiH5QZNmRdLPxKp5gOA7xp8knc60RJWp1cQ==
        -----END AGE ENCRYPTED FILE-----
  mac: ENC[AES256_GCM,data:n4ReS5jO7ntI/rFXw3V1EJ8G8qrT3GqVejDD1/XhRXKW5xhaVoS9wMrLkEjFxQgj2rtG2VtS9YCosj4oRk6+6Iy0aSpH/BNE4p5OYFhee1YoeMbl1TUhmBqzi7SEKY1LSM3cw1xj9AeBb8IA0CX6NXMW4wPWyUSI54Z83IUQ6rc=,iv:uXVbzEOAET2eX27giMv72U9v4mqSc3bbZXdLXj1zJ6g=,tag:DkBc86MT/yvBy75O9yho0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: resource-app-git-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://github.com/enschede/OAuth2ResourceAppDemo.git
  secretRef:
    name: resource-app-deploy-key

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-resource-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./src/main/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: resource-app-git-repo
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx
    - name: forgerock


