---
apiVersion: v1
data:
  known_hosts: ENC[AES256_GCM,data:UIh9FgfaLj8tKF5tDElSBKxUfyCrpk7n0JHkwlM3Gk3IcCEsmCUkFse6mnIP2GdSvFpybmX//jE2IJLPwAbrjNxjafqbV7kbP0Hs5SljtHnBdS3J4fn64jJ7IUY9HH+0UEYQg7nm+aMdim3NRSG8CN5QUZFLvMI7aNnCfQXgF9yLEmp4kiHL1kNgQFnhNjEy31qrWqXtCaMdR5o0wZ7qZg0kNh0l/rgVpHDASjYbzal85ec3kfWqw9XNKT2JYN1k9AqVzwqwhgo0SI9tYUl71HdE2QauWcsOiw8RYxHJ5TaedkiFfJPPwHzOG0Ct6ITS8uMKjgAkqerJpzB6VIl8BbC4XuxvSl7Lb0lzAEnxwvek6r5scbcpOe6FeGTgCioHIfGYl86Nrb651p7jUrjT6O9o3agpJ9xqGk4YDk1JgUrhm+M5rP5abqp5zt3Hsk+mE7nQw7f6pkf6W19lG55aAW9JYfjfZIzZtRvgdiA8teVTI/AUoti/PH8iWpOC3twcD1l1X0NgHAhAxwCvgeyXRND3l22B5EufbqXW6ehHwf6a4rgQsyY4YGoeNPchmEExU2BKI8HPHQclemW41rdbcLzP4shJo000l6IsJ0l8Wivj6VQOgUDNoz5KSfYdLZtUZXX3e+YaQrPQevDkEr6BvYLXiW4nCrEPyqZNW25E8D6bEl8ThDMeL1b4v2O/cwPHal+fY+MPCGc8aj2/HuOhlg2wnta3oSMEoG5oG2F1NZvMLwRzJQX1m1YQlSRZWmose+DzJFZnZvQdxX17yhw9LgwMD6F5pq8NRb1mQCNh7ZxqckqKlnPEEkG9/NtQRFcsEJjBfGLbJm2UsyzRhwb0Hy48N0EhqXmI7Vc6pMYyJPFKnM72TbCp/aJDCDGxLBy4X3P55V8Rq+NU1H/aaTNeUmtakT4ngjZ/k8w4fQuaRoEhXyprxRP/TM76eeP7EKq0sB3uhgSfNQm2t5QSaMkKlyi+Yn7XkHncH/983gjZOxRgnCStDULk4qUQaUWTrnH/1Bjajx/lzFQ+AGI95N7Ebp9nbqww/KxAqTsg/+g1tQU+anmfNTDRsQSuX8i84E/JW0EphIDnR/m7vVsRrCn+2Ya18fB+JBXYhlozJl6efdTa7an06a19tUXVgZvm6py8fSTgwBm43XkabYS5RIFb8bcEI8LZnpJ1M8dEwfYWUt7DCgLYWZW3w7WKjWgC2LqKE3MPEir/ltppGlTPSytkG632UMdBn/s7gTV4gLzI34+UeeITdGWkbZrnH6iZgbW7SJVIU3Fxa+2IKw3h8RNuf8aGBqlrrlwYqBvCyRc+sSK46HE+u1D+pQqBJ+XDYqyhOM+RJHbT9OP1Y5zkdbeQlliQBkRzaYwoLb06k9QcJIIT8z/IM4BLlyrCkoH+wuXkUYntCYlYHBjnXjyoUMTSZ/uer8I26nVyGbjChtBby4i2Vsd8mA9qSmiV2JycoY+tao8NOACPKXC/0DfhhuwZopglRqv9zdYBv730ox4D0tmZ3+2qC1keK1Ew92y4wWIKGKM/9R5P8a1tJtGQEYLJL/e4W0iw3iJf09OLXYyNqnLPdGP8O6N6Rn6qEhxnm9yvNjVv76BtdoLSIE2kzCJ8mLZviOQ34sZIXq6SHclqDBYUfM3X3nyuO/c4wZJYnYlBcVQe8GBWnYHpg/Yo03RhTuP6IH/3DoGJvWPMRvL2/cYYVr7s4Qk2CO9g+uUF3FnE8XJ6xQ+1WhMzvEe69y0ghl/cBlgE9FQC,iv:jIureLu03b7K8/LtP43xdNk/wbsZHNQutYC/6DCV9Rk=,tag:HWdKKOf0iq6K/LB5D8AgtQ==,type:str]
  ssh-privatekey: ENC[AES256_GCM,data:Cr2pA1lhhyu3HIl4SnMXO3M+jd42NZuTO4gTYV69MM4Elo3txZQDPWBUgA+ODiL7KWOFEBclNMA8+Uyp/0k3Oqdt9A+qIauo+tGPR0qIdxf6Fjz0tWr9sbDFtkOoVaFcCeWYZvMnMWDTLlRXmwWhTjyla18SZPCWtnL0Gg+7VQmEiaa8dG/Gm/+JtHkYT/aJMdzmIs8fJvMV1mn1Tet72iAo1RjHlUxoo2cZtFniGSRtMibVbNOzH7UDgIDChvk2VV4Uee7HIScvHfsZ6ty584X4u6/6oxds1bQvSWLJz21ketfdBfGLSQE3SLQeVaUJti9nk1z0Bxvi+DkysslNoMEaqwYMjkZP25Ml988ly6eRmxAPHHF+Tmtg4voiPnnYgHlZLKDb1NtlWVs/uKHknZPDtojxdtxi4SufnLslymJ4++VIwOI2ITRFVIEEsJ1a8R8HPn5PQy8gc8ObQczsCBZFBUcukY/8g5PszlyMoKQoOwRUDe1R98uPHkoLLd5/sCOCgTU5q/heJs99hrGFkypy3P2T1ekI7tc/NTEeoIl7fpphI8xcx5gkkiJCyg82Z9noyw6fWeOsxyP0wtfTY7RRgzBh4OySpYXgCg/3PRYH9cbfK/7+uQPJ5jXLtFsvs7snJ9PsTwriF8J/TpuA3sWxHlxhQcewhnpYf+EYaOPnyAGo121H8LQi/sYCfJU1ohxSFHp0mwcC4gSE4dDTinvMTdKVycloaSmKmZUOo2YCMW+TLIyr1VXyzBlr/Zt/,iv:J7/hkFbGMATgZ54C+ez+9ykk377OmkBmrdoo5V6Xfvo=,tag:lhPDfvsmM3MVGlWy6V/4dw==,type:str]
kind: Secret
metadata:
  name: client-app-deploy-key
type: kubernetes.io/ssh-auth
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYUZyRSt2M2ZuZWxMaUxZ
        ZFlDRDFleUwyWDZnNUtFd25YK0xTaW9Vb0FRCmRVVFA2RUlCNW54TVNmKzNRaGxr
        MGxQWVd0YURwZHU1dEhCemNubDJHUlUKLS0tICtOU0xVYWkyUnhwOGpFV2tsejB5
        SE04Y3hMRk95VE9aOVRQUEJiaGpiNlkKK/uxaGEznFhMP8xx5iYwNHP7dT1bSEGK
        nZK1TeqEskaWfaniZzjb2AsR9qeTJeqWaw5REMnwjWSlYHjMafawGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T18:43:11Z"
  mac: ENC[AES256_GCM,data:dfXulg3CiPkHQ7iu9ybsstyxCUQ1Zya1z2iMx0jK+tj88XlRxe1jR+tO5y2e1aHpTUnJ1yPh/EbzqR7CUweIIhs6Drw4DyQCqOBwY+J58ogEusxdUIgFOyGel5+8gNJtWmWlV2QEDFC+Hrv5RMQ7zkWd5FfZDmx5VWN8Lou+xKg=,iv:VcL41j7Ruro8i/xoZzHo/xk6PJcgeVPbe8YODaRNHF4=,tag:lCNaLv2MhgLPawhg2rnbkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: client-app-git-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ssh://github.com/enschede/OAuth2ClientAppDemo.git
  secretRef:
    name: client-app-deploy-key

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-client-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./src/main/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: client-app-git-repo
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: forgerock


