apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/part-of: ingress

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      # version: "4.x.x"      # optioneel pinnen
  values:
    controller:
      ingressClassResource:
        name: nginx
        default: true
      service:
        type: LoadBalancer    # Bare-metal? Gebruik MetalLB of zet 'NodePort' met vaste poorten
      replicaCount: 1
