---
apiVersion: v1
kind: Secret
metadata:
  name: client-app-deploy-key
  namespace: flux-system
data:
  identity: ENC[AES256_GCM,data:jfMe5NHmyD+IXTUI64m8KDiISkGqkG/YS0Jqrl0oKRjPu1T0IVK5+VTfNGy8sOy+yfUQLTkuKwiqTiIOFnOZAC67OtELX0Y1iUO3eynkql8v1cSteM+BQOzp+upf8Ck+rjUbTv7uDY0m3e9jRLa+9cX0njMg9092k4eC/LitdD+4iYpYJmhvucdHaTSET2CNCsa4sAOa03u4t/vEaui47FiLnWOpcN2RrfqW+c1cWjBNbXEkPz7OB2tPOy6F9F4W0dwNBCCgYcm7CuWNZ0vUqyq0JQd2x9sKF8tojcSiCZnyQqn5jRmcV0ml91vvm43GYxa+i2iUlGkMO9ic1qNA0BzUYKME2ddsComvAndKVv/eErIQ9ZGg79T22BaYFfGXXhFvCrn9SJcP8+IjJ1rbuSdQt6vejPJCFdoV0NqN9vB1YAmz4GH1ncrHpPIRtrzdHmeEXQtvCFBXHOm9kvAJHYjreWeYxoHavPJG/n8+cdkCvLDJq/5pNR3HUxPrTS17JnfBVEQz2cHQy29/qJw77++BcLSEI2C69WGu24nTsHfyVJC4keyo5f8Wzk+cv+vWgtNS8tR6HeCwRj3xWvY4dCcmtzUD9dcgtYFb204SwrHUB2sBVoTaKMt83b1yLrVhBWYEHWXURyYFVsf61QQhdSn+94bzBq96bbF0AsUiqLj5fF6msU9oE6xFjNCqcZQcMW6EyMu+pCefQ6woqwAVw3tMH7sogX4V6ryAaEoModiGwcXQN6AggCP3hKHTuSif,iv:WlWy0XMmeTjguBIclONEupTgXSj4q2MWUV70NFf4TNM=,tag:S5ImmmjXJQuzDimERPdzvQ==,type:str]
  identity.pub: ENC[AES256_GCM,data:Y9jf3y75n5LlVcmz9VlVggjZ8S1Pz/nLkDa929YgqvbaY7bCjtUn3Cm22C1XFISltONySX/nEIQBXOpiHiwYFveA4snUqy+mTmL0DtRgRei4RVzvVogFFOciCB18/J8abRs9IrwBJzfQqW7Clgen7SRq5UwjE12ni3Y81QHrV/gTwkUcq1BhxIdcV/rWlWLG+DLDc7ET4+U=,iv:sYp0WTk+lLmkjhBZ+E9eDz+vHAErPSS0XLG/WV4G4Hg=,tag:Ws4ckVj3rnz7SaoHmv9zGw==,type:str]
  known_hosts: ENC[AES256_GCM,data:4pqKEZtZTc9UhGyAh4CsFmNCJaD6MPoxsQJSU8g/oE0yiDbx4Wg5AxF88ltsPnu0aJknZDwkd8U0k5sus7zGAwKrvex4A0rw0/d05Dx4zmq/LDVl3YGtMw7q+jm+0OyuOOHZIA6MyYso6R3uJX5sNrig0KqOIaP8i1nxCLLiqRawKRteUQPPj29AOGwrEqj0eS4i6csN8bTOjK4rv/ipF78JFE8ggV+xCYeAtBRCdTTq+i4+U0qsQa4lY9/NyJAlorhFlMekAgCkhnK9LBLe7Je24ZMaPOdG1HUbznrY7x2XbObK1+otzbGwchrVxENVgXsStgRpQEYvpv2JzB1/QZngPHnTAy0S2ig9/d9JyQrNEIEIuQb8VyPs8HOh3zO51fYq7DKO41c2StBX6BYQj8WK8gFLecE8qSIHj0mBhoT6Exvj/wsD/eq/F3ZkSbNU2SbBT2JtfjbH3eGoFT6pXUzOUtSzxLSnTGu1lKgR5VFqliVRKPb5buBiGfv3kPonF7syr4HhKkG+aBmsvhm2N9ENmJ0qibA6URRV75la5XwVvQokjGUmCTI8e4sZfGmFkjrBMelO5lBNyKL//BxvB5WfWTi2YXkn36mgZ0sM/+y1AjrOA07mngYvoEkC1HjZ+rlwEKurb3Bh3g08+BVJhZrsqZ/bKe1v39czvFy2Fm7skWtrQiaiq+FG2y16y7n4BDjlVP4w6vHGgYmGjRGyLbCsYhlKmZSjTid5VG3jtx+1gzp3+niabbiGf9HY5HWaDxviZdz5hlLP9WRdjxrX0K/KjK+kbzU3yGggN1C+U1GpWEX6UNniyI6tTQwP8EiOGf+s5glvrt3lXGMHCj2JYhGEsoqfJsEMEF/y+R29OJ4jA7ioI9K6iprioiakpOFABEyKvPH1gm7k1RIywn2M2ZJAgGzTwsZnJreWsN9qldtaZ6rzaBsSl9YWh/+xyq11gA4YroZhjl/CghsPlijOBVgSnVJ6Pa983tuTYXIiva3XIDAP9beTzAQUXAU6I3HgN187bXPntuofTkQE+Gqxq5wlbhP9GKHsZYBXGtYSDws/qDi2OFVezLdKwiMaK/mAQAjSWmA9SxsyShU2Ue2YvcwuFuJij1WA486nl7swwButCcBgOx3UzU4oQf7Y7apF3TN9tbbQKecuWll/tZ5jpOSrNIrWUWjnGIS70N++b2FgtDxLpZyjM+p4MYT6XRvWdDhSUlUCV21q3x/ff4guLF8+eXFHod4Q9e5lVKSomLQX3nOuRY3elVjIYMT7WNj5yrvQW5xyR0vW24BQ5404ZcvjqGJhYlBER8tLCck0/Aj1FT5jBdpA5C1Nlx6kXge2j0Lwn+lfj17UOhhME9lMEZ8T0UsvgJjrdvA1xfF3HQb/rkbh4sD0x8FgqtkjxMsWKs8fKCPjdIufE5TO2OT4lZsSj8BOvL1j3tByre+w+xVOv2NQtMAzUfVYSwDKlg6maf1V9KnVLzfo/mfKMDQta8AnrZ6bo91GiK+1FIKzj/EY210jxUp+l/o1yofPsZ3HSvTkQytgObMWw16rmhLKFt9ZbmByZ9zcOp9Mdee6xdArx9oE0ln81yWQptmmLqhlb26uFb5QXmm6JeUPgD0hcjrvS8Dw029xu8xB7luMMA2F7jDE/Q6NXhp14GY/ErDvXY5mSnhcdFAP9KMcZBx+Ez06++hc+7a9Ccdw/gyAdN4FqDWGleLUyvrb1c/2oKObC/9235/Y/pDIw62J0/BH0yJMnZyyfjJ7,iv:8p4KcvdQuJALBokjlAEBTUonhoVytEEFq1Qx+HWAF6Q=,tag:qmpjhCDi52J3P7AxPHSzqg==,type:str]
sops:
  age:
    - recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMitZNzVKaDhLZm05emlw
        OWt2cUVVcGpEamY1RDV5MXJyS0daM0pJcHlvCmxNUEZlTS9nVXk5RXhkQTRHdDcw
        MTFqdFltcmlteTBTUFZqbHBhdERnNkkKLS0tIE8yN3N1TzBJNVVabWI5QTJ3ZGx4
        R1RqcHl2bnFEZmN3NStpSis2MUpVUTAK2DPXxMGWgXTAK/lDsPuw9X0Z7pnZeBld
        KFnCwU8gzXG/+0fovi2PhWqDU+W7tvELMIrwKTVEyWdPDClOIcD5Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T18:10:05Z"
  mac: ENC[AES256_GCM,data:/qM4apu9uWnXcMGz+CmZWGaMewp3wvp6spv+rGe08sGoa/vCYil4duWNKMO1rbPuB5nfEL/nxZQWRevJ9yiG689UlX8MNiWGXydQuEzz0bIOsmaucEuW6pGin3zC/g1hqS/UUKngSY7x1q4Uwj00icNROm0JNf6U1l0pAkvAnZo=,iv:FW7WbMkbFBy7mScq99Hk7WXXzb5E68Bl8ufgI9f/3O8=,tag:Uno+r81SR++uwVFz053YgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: client-app-git-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://github.com/enschede/OAuth2ClientAppDemo.git
  secretRef:
    name: client-app-deploy-key

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-client-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./src/main/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: client-app-git-repo
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ingress-nginx
    - name: forgerock
    - name: oauth2-resource-app
