apiVersion: v1
kind: Secret
metadata:
    name: amadmin-password
    namespace: ping-platform
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:4SSH1lP0aw==,iv:uCNAu6adAZhi6DxUuF9ZNO34N8VNM2WksFK6js2U2fA=,tag:Ytt6NnrQBRVPDRDUC0ydZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORHJrVXNtR2FIeDBoNld3
            b2pRQi9UY3pwblVwTlBadERKOFVFanhPb0RVCmEvRWx0MDRjamQwYXVBZzNEZU5Z
            YTlLQ1JGMHdDcXU4TVBZS1dYeTZGSWcKLS0tIGZVSzFlVnVJSG54TStRYzU3WE4z
            dG5iQURtQkVta0hVTU9zbzE2dUNYbG8KIm7gr612LarnQYCrj2Oi7sTDEF7PfQou
            akw3WH5/fRgFH+vWjQmZmvQ4IzPkEJDWCAOSXZj8/sRalMs8gYk74g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1spe3avhtcgkgqujprtujackxw6au5h8tum6nk6czmxgaclprx5tsz9jrhr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T21:01:45Z"
    mac: ENC[AES256_GCM,data:PN+MYiQcI71MLggdVSbDnF5oo28L7OPb1GGIbYnlpY2SgWTrN5XeLj4IkigAcutPNkHnt433i5SuNJCMeYFGR1V2lThmRerE/0p/MjmGxVrvXH2+wHORuYgLL3V05XglrkkRQyGh3QWKgQuQaoRAzrmjS86hk8Jh7KAVL8HKm8U=,iv:Q6xdi5xkmTYVOnzAfbKSPhCN/HM1xbaK4ZGgmFbFUtc=,tag:UcmQquAwTJcsNf4jZ/hZ2g==,type:str]
    version: 3.13.2
