apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: forgeops
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: identity-platform
      version: "2026.2.1"
      sourceRef:
        kind: HelmRepository
        name: forgeops-helmrepository
        namespace: flux-system
      interval: 1m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: identity-platform-values
      valuesKey: values.yaml

#  postRenderers:
#    - kustomize:
#        patches:
#          - target:
#              kind: Ingress
#              namespace: ping-platform
#            patch: |
#              - op: add
#                path: /metadata/annotations/traefik.ingress.kubernetes.io~1service.serversscheme
#                value: https