am:
  replicaCount: 1
  podSecurityContext:
    runAsUser: 11111
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - All
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  secrets:
    amAdminPassword:
      existingSecret: amadmin-password
      passwordKey: password

ds_cts:
  replicaCount: 1
  podSecurityContext:
    runAsUser: 11111
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - All
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 11111
idm:
  replicaCount: 1
  podSecurityContext:
    runAsUser: 11111
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - All
    readOnlyRootFilesystem: true
    runAsNonRoot: true
ds_idrepo:
  replicaCount: 1
  podSecurityContext:
    runAsUser: 11111
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - All
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 11111
ig:
  replicaCount: 1
platform:
  ingress:
    hosts:
    - sso.worldofciam.nl
    className: traefik
    tls:
      issuer:
        kind: ClusterIssuer
        name: my-cluster-issuer
      secret:
        name: worldofciamnl
admin_ui:
  podSecurityContext:
    runAsUser: 101
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - All
    readOnlyRootFilesystem: true
    runAsNonRoot: true
login_ui:
  podSecurityContext:
    runAsUser: 101
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - All
    readOnlyRootFilesystem: true
    runAsNonRoot: true
end_user_ui:
  podSecurityContext:
    runAsUser: 101
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - All
    readOnlyRootFilesystem: true
    runAsNonRoot: true
